#:schema node_modules/wrangler/config-schema.json
name = "workers-ai-image-playground"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[[r2_buckets]]
bucket_name = "ai-img-playground"
binding = "BUCKET"

[vars]
CLOUDFLARE_ACCOUNT_ID = "f6c275d1df80684efe4d1b773917f6d3"
CLOUDFLARE_API_TOKEN = "8xzfnwwC-hwLmFcOSzxPpGPebb_Gn1IyXxdF7QHo"
